#!/usr/bin/env python3
"""Regenerate docs/dropped-tests.md, the record of why tests are dropped per project.

Combines benchmark-side ignores from ProgramBench's tests.json with each fork's
course-side .programbench/local_ignored_tests.txt. Run after recording a project
with update_readme.py, then commit and push both files.
"""

import json
import re
from collections import Counter
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent
DEST_ROOT = ROOT.parent
TASKS_DIR = Path.home() / "Code/ProgramBench/src/programbench/data/tasks"
FORK_RENAMES = {"astaxie/bat": "bat-astaxie", "sharkdp/bat": "bat-sharkdp"}

REASONS = {
    "gold_fail": "fails deterministically on the original (gold) binary",
    "gold_flaky": "nondeterministic on the gold binary, passes in some runs and fails in others",
    "dummy_pass": "passes even on a trivial stub executable, so it distinguishes nothing",
    "outcome_dependent_presence": "appears in some evaluation runs but not others",
    "slow_or_hang": "hangs mid-call or exceeds a duration threshold",
    "dependency_ignored": "depends on another ignored test via pytest dependency marks",
    "ignored_manual": "manually excluded by the benchmark authors",
}

HEADER = """# Why tests are dropped

Each ported project keeps every reliable ProgramBench test and drops the rest. A drop always
has one of two origins, and every drop is recorded here.

**Benchmark-side drops** come from ProgramBench itself: its `tests.json` marks individual
tests (and occasionally whole test branches) as unreliable, and they are excluded from
scoring everywhere, containers included. The reason codes are:

"""

HEADER2 = """
**Course-side drops** are our own exclusions, listed in `.programbench/local_ignored_tests.txt`
inside each fork. These tests are correct inside the benchmark's Linux containers but depend on
that environment (container paths, root privileges, Linux-only devices, filesystem ordering,
CPU architecture, or dependency resolution), so they cannot hold on every student machine.
Each entry below quotes the reason recorded in the fork.

This file is regenerated by `tools/gen_dropped_tests.py`; do not edit it by hand.
"""


def local_exclusions(path: Path) -> list[tuple[str, list[str]]]:
    body = path.read_text().split("\n\n", 1)[1]
    groups: list[list] = []
    comment: list[str] = []
    for line in map(str.strip, body.splitlines()):
        if line.startswith("#"):
            comment.append(line.lstrip("#").strip())
        elif line:
            if comment:
                groups.append([" ".join(comment), []])
                comment = []
            groups[-1][1].append(line)
    return [(reason, tests) for reason, tests in groups]


def main() -> None:
    by_repo = {}
    for t in sorted(TASKS_DIR.iterdir()):
        task = dict(
            line.split(": ", 1) for line in (t / "task.yaml").read_text().splitlines() if ": " in line
        )
        by_repo[task["repository"]] = t.name

    rows = re.findall(
        r"^\| \[([^]]+)\]\([^)]+\) \| `[0-9a-f]{7}` \| (\d+) \| (\d+) \|",
        (ROOT / "README.md").read_text(),
        re.M,
    )

    out = [HEADER]
    out.append("".join(f"- `{rid}`: {desc}\n" for rid, desc in REASONS.items()))
    out.append(HEADER2)

    for repo, shipped, kept in rows:
        iid = by_repo[repo]
        branches = json.loads((TASKS_DIR / iid / "tests.json").read_text())["branches"]
        fork_dir = DEST_ROOT / FORK_RENAMES.get(repo, repo.split("/")[1])

        out.append(f"\n## {repo}\n\n")
        out.append(f"Instance `{iid}`: {shipped} tests shipped, {kept} kept.\n\n")

        reason_counts: Counter[str] = Counter()
        n_bench = 0
        for info in branches.values():
            if info.get("ignored"):
                continue
            for t in info.get("ignored_tests") or []:
                n_bench += 1
                reason_counts.update(r["id"] for r in t["reasons"])
        out.append(f"Benchmark-side: {n_bench} tests dropped by ProgramBench.\n\n")
        for rid, n in reason_counts.most_common():
            out.append(f"- `{rid}`: {n}\n")

        ignored_branches = [(b, info) for b, info in sorted(branches.items()) if info.get("ignored")]
        if ignored_branches:
            out.append("\nWhole branches dropped by ProgramBench:\n\n")
            for b, info in ignored_branches:
                reason = info.get("ignore_reason") or "no reason recorded"
                out.append(f"- `{b}` ({len(info['tests'])} tests): {reason}\n")

        # Read course-side exclusions from the durable snapshot committed under
        # docs/exclusions/ (clones get pruned at wave end). Snapshots are
        # refreshed from the live clone when present so they stay current.
        snapshot = ROOT / "docs" / "exclusions" / f"{iid}.txt"
        clone_local = fork_dir / ".programbench/local_ignored_tests.txt"
        if clone_local.exists():
            snapshot.write_text(clone_local.read_text())
        local = snapshot
        if local.exists():
            groups = local_exclusions(local)
            n_local = sum(len(tests) for _, tests in groups)
            out.append(f"\nCourse-side: {n_local} tests dropped by us.\n\n")
            for reason, tests in groups:
                out.append(f"- {reason}\n")
                out.extend(f"  - `{t}`\n" for t in tests)
        else:
            out.append("\nCourse-side: none.\n")

    doc = ROOT / "docs" / "dropped-tests.md"
    doc.write_text("".join(out))
    print(f"wrote {doc} covering {len(rows)} ported projects")


if __name__ == "__main__":
    main()
